name = "harpertoken-github-status"
main = "src/index.js"
compatibility_date = "2026-04-12"

[vars]
ORG = "coccinella-labs"
RELEASE_REPO = "coccinella-labs/harper"
SITE_REPO = "coccinella-labs/harpertoken.github.io"
DISCUSSION_REPO = "coccinella-labs/harpertoken.github.io"

